# Generated by Django 5.0.3 on 2024-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='address',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='city',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='first_name',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='insurance_type',
            field=models.BinaryField(choices=[('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('life', 'Life Insurance')]),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='last_name',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='state',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='zip_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
