# Generated by Django 5.0.3 on 2024-04-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0002_alter_insurancedata_address_alter_insurancedata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='insurance_type',
            field=models.TextField(choices=[('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('life', 'Life Insurance')]),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='state',
            field=models.TextField(),
        ),
    ]
