# Generated by Django 5.0.3 on 2024-04-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0003_alter_insurancedata_address_alter_insurancedata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
