# Generated by Django 5.0.3 on 2024-04-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0004_alter_insurancedata_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='insurance_type',
            field=models.CharField(choices=[('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('life', 'Life Insurance')], max_length=255),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
