# Generated by Django 5.0.3 on 2024-04-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0005_alter_insurancedata_address_alter_insurancedata_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='enc_first_name',
            field=models.BinaryField(default=b''),
        ),
    ]
