# Generated by Django 5.0.3 on 2024-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0006_insurancedata_enc_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='enc_last_name',
            field=models.BinaryField(default=b''),
        ),
    ]
