# Generated by Django 5.0.3 on 2024-04-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0007_insurancedata_enc_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='enc_first_name',
            field=models.BinaryField(null=True),
        ),
    ]
