# Generated by Django 5.0.3 on 2024-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0008_alter_insurancedata_enc_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
