# Generated by Django 5.0.3 on 2024-04-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0009_insurancedata_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='enc_address',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_city',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_insurance_type',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_state',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='enc_last_name',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='insurance_type',
            field=models.CharField(choices=[('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('life', 'Life Insurance')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
