# Generated by Django 5.0.3 on 2024-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0011_insurancedata_enc_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='enc_coverage_amount',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_email',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_end_date',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_phone_number',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_start_date',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_zip_code',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
