# Generated by Django 5.0.3 on 2024-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0017_remove_insurancedata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='name_convention',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
