# Generated by Django 5.0.3 on 2024-04-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0018_insurancedata_name_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='chronic_disease',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('heart_disease', 'Heart Disease'), ('cancer', 'Cancer'), ('arthritis', 'Arthritis'), ('asthma', 'Asthma'), ('copd', 'Chronic Obstructive Pulmonary Disease (COPD)'), ('depression', 'Depression'), ('osteoporosis', 'Osteoporosis'), ('alzheimers', "Alzheimer's Disease"), ('stroke', 'Stroke'), ('kidney_disease', 'Kidney Disease'), ('multiple_sclerosis', 'Multiple Sclerosis'), ('lupus', 'Lupus'), ('crohns_disease', "Crohn's Disease"), ('fibromyalgia', 'Fibromyalgia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_chronic_disease',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_gender',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_height',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_weight',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
