# Generated by Django 5.0.3 on 2024-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0019_insurancedata_chronic_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='chronic_disease',
            field=models.CharField(choices=[('alzheimers', "Alzheimer's Disease"), ('arthritis', 'Arthritis'), ('asthma', 'Asthma'), ('cancer', 'Cancer'), ('copd', 'Chronic Obstructive Pulmonary Disease (COPD)'), ('crohns_disease', "Crohn's Disease"), ('depression', 'Depression'), ('diabetes', 'Diabetes'), ('fibromyalgia', 'Fibromyalgia'), ('heart_disease', 'Heart Disease'), ('hypertension', 'Hypertension'), ('kidney_disease', 'Kidney Disease'), ('lupus', 'Lupus'), ('multiple_sclerosis', 'Multiple Sclerosis'), ('osteoporosis', 'Osteoporosis'), ('stroke', 'Stroke')], max_length=50, null=True),
        ),
    ]
