# Generated by Django 5.0.3 on 2024-04-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0020_alter_insurancedata_chronic_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancedata',
            name='chronic_disease',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='enc_chronic_disease',
        ),
    ]
