# Generated by Django 5.0.3 on 2024-04-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0021_remove_insurancedata_chronic_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedata',
            name='dl_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_dl_no',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='enc_license_plate',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='license_plate',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='insurance_type',
            field=models.CharField(choices=[('health', 'Health Insurance'), ('auto', 'Auto Insurance')], max_length=255, null=True),
        ),
    ]
